stages:
- english
- translations
.build-common: &common
  before_script:
  - apt-get update
  - apt-get -y install wml make gettext git opencc diffstat libintl-perl libxml-rss-perl wget libtimedate-perl
# english, which we do always
english:
  <<: *common
  stage: english
  image: debian:stretch
  script:
  - make LANGUAGES=english install
  after_script:
  - mkdir -p .public
  - mv ../www .public/english
  artifacts:
    paths:
      - .public
# translations
.build: &build
  <<: *common
  image: debian:stretch
  stage: translations
  retry: 2
  script:
  - if [ ! -z "$(git log -p ${CI_COMMIT_BEFORE_SHA}..HEAD|diffstat -p1 -l|grep '/'|cut -d'/' -f1|uniq|grep ${CI_JOB_NAME})" ]; then make LANGUAGES=${CI_JOB_NAME} install; else echo "no changes for $CI_JOB_NAME"; fi
  after_script:
  - mkdir -p .public
  - mv ../www .public/${CI_JOB_NAME}
  artifacts:
    paths:
      - .public
albanian:
  <<: *build
arabic:
  <<: *build
armenian:
  <<: *build
bulgarian:
  <<: *build
catalan:
  <<: *build
chinese:
  <<: *build
croatian:
  <<: *build
czech:
  <<: *build
danish:
  <<: *build
dutch:
  <<: *build
esperanto:
  <<: *build
finnish:
  <<: *build
french:
  <<: *build
galician:
  <<: *build
german:
  <<: *build
greek:
  <<: *build
hebrew:
  <<: *build
hungarian:
  <<: *build
indonesian:
  <<: *build
italian:
  <<: *build
japanese:
  <<: *build
korean:
  <<: *build
lithuanian:
  <<: *build
norwegian:
  <<: *build
persian:
  <<: *build
polish:
  <<: *build
portuguese:
  <<: *build
romanian:
  <<: *build
russian:
  <<: *build
slovak:
  <<: *build
slovene:
  <<: *build
spanish:
  <<: *build
swedish:
  <<: *build
tamil:
  <<: *build
turkish:
  <<: *build
ukrainian:
  <<: *build
vietnamese:
  <<: *build
