stages:
- english
- translations
- merge
# english, which we do always
english:
  stage: english
  image: registry.salsa.debian.org/webmaster-team/webwml/build:latest
  script:
  - make LANGUAGES=english STRICT_ERROR_CHECKS=1 USE_SAMPLE_FILES=1 install
  after_script:
  - mkdir -p .public
  - mv ../www .public/english
  artifacts:
    untracked: true
    when: always
    paths:
      - .public
# translations
.build: &build
  image: registry.salsa.debian.org/webmaster-team/webwml/build:latest
  stage: translations
  retry: 2
  script:
  - if ci/build-me; then make LANGUAGES=${CI_JOB_NAME} STRICT_ERROR_CHECKS=1 USE_SAMPLE_FILES=1 install; else echo "no changes for $CI_JOB_NAME"; fi
  after_script:
  - mkdir -p .public
  - mv ../www .public/${CI_JOB_NAME}
  artifacts:
    when: always
    paths:
      - .public/$CI_JOB_NAME
merge:
  stage: merge
  image: debian:stretch
  before_script:
  - apt-get update
  - apt-get -y install rsync
  script:
  - mkdir -p public
  - for i in .public/*; do rsync -a $i/ public/; done
  artifacts:
    paths:
      - public
albanian:
  <<: *build
arabic:
  <<: *build
armenian:
  <<: *build
bulgarian:
  <<: *build
catalan:
  <<: *build
chinese:
  <<: *build
croatian:
  <<: *build
czech:
  <<: *build
danish:
  <<: *build
dutch:
  <<: *build
esperanto:
  <<: *build
finnish:
  <<: *build
french:
  <<: *build
galician:
  <<: *build
german:
  <<: *build
greek:
  <<: *build
hebrew:
  <<: *build
hungarian:
  <<: *build
indonesian:
  <<: *build
italian:
  <<: *build
japanese:
  <<: *build
korean:
  <<: *build
lithuanian:
  <<: *build
norwegian:
  <<: *build
persian:
  <<: *build
polish:
  <<: *build
portuguese:
  <<: *build
romanian:
  <<: *build
russian:
  <<: *build
slovak:
  <<: *build
slovene:
  <<: *build
spanish:
  <<: *build
swedish:
  <<: *build
tamil:
  <<: *build
turkish:
  <<: *build
ukrainian:
  <<: *build
vietnamese:
  <<: *build
